"""added password to user

Revision ID: 6da3fba3aad0
Revises: e4d59f89d861
Create Date: 2026-01-01 12:44:44.228925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da3fba3aad0'
down_revision: Union[str, Sequence[str], None] = 'e4d59f89d861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password'), table_name='users')
    # ### end Alembic commands ###
